navikt/familie-brev

src/App.tsx, src/components/meny/Meny.tsx, src/components/meny/MenyVariabler.tsx, src/hooks/useLocalStorage.ts
Så slipper man å velge dokumentet man jobber med på ny hver gang man har gjort en endring i Sanity.
=> Bruk localStorage for å huske dokumenter mellom pageloads

package.json, src/App.tsx, src/hooks/useLocalStorageOrQueryParam.ts, yarn.lock
Sjekker queryparams før man henter brevtype-verdi fra localStorage. Gjør at man får åpnet riktig brevtype fra dokumentet i Sanity.
=> Hent brevtype fra queryparams

src/server/components/AvansertDokument.tsx, src/server/components/Dokument.tsx, src/server/components/serializers/blockSerializer.tsx, src/server/components/serializers/delmalSerializer.tsx, src/server/components/serializers/lenkeSerializer.tsx, src/server/components/serializers/listItemSerializer.tsx, src/server/utils/css.ts, src/server/utils/openhtmltopdfBughåndtering.tsx
https://github.com/navikt/familie-sanity-brev/pull/24
=> Legg til markering av lenke slik at lenker ikke brekker ved slash

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
- Forenkle navn på workflows for lesbarhet ved workflow dispatch.
- Foreslår litt strengere regel for deploy til dev nå som appen er på og folk plutselig skal ha demo, teste etc. Pull requester deployer som vanlig, men deployer ikke lenger ved alle pushes pga wip-deling av kode. Hvis man vil ha det i dev må det trigges manuelt.
=> Små endringer i workflow-trigging

src/server/components/serializers/ValgfeltSerializer.tsx
=> Send med riktig type i valgfeltSerializer

src/server/hentAvansertDokumentHtml.tsx, src/server/routes.ts, src/typer/dokumentApi.ts
Sender med signaturer, utenfor sanity-data ved generering av avansert dokument.
=> Signatur i AvansertDokument

src/server/hentAvansertDokumentHtml.tsx, src/server/utils/css.ts
Enkel styling av signatur i brev.
=> Styling signatur avansert dokument

src/server/components/Header.tsx, src/server/hentAvansertDokumentHtml.tsx, src/server/hentDokumentHtml.tsx
Endre navnet på brevdatoen fra dato til brevOpprettetDato
=> Brev dato navn

src/server/hentAvansertDokumentFelter.ts
Løser [denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5916) oppgaven.
=> Legg til gruppeVisningsnavn

.github/dependabot.yml
For å ikke spamme ned pr-kanal
=> Endrer dependabot til weekly

src/server/components/Brevhode.tsx, src/server/lagManueltBrevHtml.tsx, src/server/routes.ts, src/typer/dokumentApi.ts, src/utils/dato.ts
Legger til muligheten for å lage brev med tilpasset innhold.
[Favro-sak.](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6218)
Hører til [denne PRen på familie-ef-sak-frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/519).
=> Manuelt brev

src/server/lagManueltBrevHtml.tsx
Denne kan sikkert løses mer elegant, men det jeg fikk til på 2min 😅
=> Underoverskrift skal formaterer likt i fritekstbrev som i sanitybrev

Dockerfile
=> Oppgraderer docker for å fikse datoformatering

.build/nais-dev.yaml, .build/nais-prod.yaml, src/server/routes.ts, src/server/søknadgenerator.tsx, src/server/utils/soknad-css.ts, src/typer/dokumentApi.ts
Utkast for å generere pdf for EF-søknader. Hadde vært fint å rekjørt en task og se diff mellom ny/gammel versjon.
=> Generer soknad pdf

src/server/hentAvansertDokumentNavn.ts, src/server/routes.ts
Co-authored-by: Mattis Janitz <mattis.janitz@nav.no>
=> Skal kunne hente upubliserte brevmaler

package.json, yarn.lock
Reverts navikt/familie-brev#201
=> Revert "Bump @testing-library/react from 9.5.0 to 12.1.2"

.husky/pre-commit, package.json, yarn.lock
Reverts navikt/familie-brev#200
=> Revert "Oppdater gamler npm-pakker"

src/server/lagManueltBrevHtml.tsx, src/typer/dokumentApi.ts
For kode6 saker skal vi bruke en spesiell signatur, med NAV Vikafossen som enhet. Derfor trengs enhet å kunne settes manuelt.
=> Vil kunne sette enhet i signatur

package.json, yarn.lock
Var allerede lagt til i `.eslintrc`, men ikke i `package.json` så eslint kunne ikke lastes riktig.
=> Legger til eslint-plugin-react-app

src/server/hentAvansertDokumentHtml.tsx
Co-authored-by: Mattis Janitz <mattis.janitz@nav.no>
=> Skal ikke vise bindestrek etter saksbehandlers signatur

src/ba-sak/formateringer.ts, src/ba-sak/formateringsvalg.ts, src/ba-sak/typer.ts
Fjerne kombinasjonen av du får og du har rett til, da det kun skal være mulig å velge en av de.
=> Fjerne logikk for du får OG du har rett til

src/ba-sak/queries.ts
Opprydning av denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8425
=> Fjern trigger som ikke skal brukes lenger fra query

src/ba-sak/formateringer.ts, src/ba-sak/formateringsvalg.ts, src/ba-sak/typer.ts
Legg til søker aktivitet og "søkersAktivitetValg" i formaterValgfelt
=> Legg til søkersAktivitetValg

src/server/components/serializers/PeriodeSerializer.tsx
=> Legg til funksjonalitet for å bygge EØS-begrunnelser når perioder skal genereres

src/ba-sak/formateringer.ts, src/ba-sak/formateringsvalg.ts, src/ba-sak/typer.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8968
Litt usikker på hvordan jeg får testet valgfeltet uten å prodsette, men det er i alle fall ikke i bruk i noen dokumenter ennå. Har laget valgfeltet og delmalene: 
https://familie-brev.sanity.studio/ba-brev/desk/valgfelt;44a17a41-a760-44f7-8d7d-a3cf1676b85a
https://familie-brev.sanity.studio/ba-brev/desk/delmal;eos;annenForeldersAktivitet
=> EØS: valgfelt for annen forelders aktivitet

package.json, yarn.lock
Oppgradert passport i familie-backend
=> Oppgrader familie-backend til nyeste versjon

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .github/workflows/build_pr.yaml, Dockerfile
Ta i bruk node 16 som er aktiv LTS
=> Ta i bruk node 16 som er aktiv LTS

package.json, yarn.lock
Endrer kun pakker i devDependencies, så om denne bygger burde det være good
=> Oppdaterer pakker og fjerer pakker vi ikke trenger

LICENSE
* :page_facing_up: Add license
* :pencil2: Typo
* Rename LICENSE.md to LICENSE
Ser ut som deres foretrukne navngivning
Co-authored-by: halvorbmundal <halvorbmundal@users.noreply.github.com>
=> :page_facing_up: Add license (#329)

src/ba-sak/formateringsvalg.ts, src/ba-sak/typer.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9639
Legger til valgmulighet når søkersaktivitet = inaktiv.
=> Åpne opp for begrunnelser når søkers aktivitet er inaktiv

src/server/components/Header.tsx, src/server/components/serializers/ValgfeltSerializer.tsx, src/server/hentAvansertDokumentHtml.tsx, src/server/lagManueltBrevHtml.tsx, src/server/routes.ts, src/typer/dokumentApi.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10080
* Param `datoVedtatt`, er det greit? Tenker man då kan sende inn undefined, eller placeholder, (eller tom et dato hvis ønskelig). 
* https://github.com/navikt/familie-ef-sak/pull/1847
=> Dato brev beslutter

.gitignore, src/baks/formateringsvalg.ts, src/baks/typer.ts
Denne henger sammen med, men kan trygt merges før, https://github.com/navikt/familie-ba-sak/pull/3022/
=> Støtt gjelderSoker for EØS-begrunnelser

src/baks/formateringer.ts, src/baks/formateringsvalg.ts, src/baks/typer.ts
Legger til nytt valgfelt for **_`du eller du og den andre forelderen`_*
https://favro.com/organization/98c34fb974ce445eac854de0/077068028bffba85055cca2d?card=Tea-10659
=> Nytt valgfelt du eller du og annen forelder

README.md
Som følge av endring: https://github.com/navikt/familie-dokument/pull/339
=> Endret readme etter renaming av klasse i familie-dokument

src/baks/formateringsvalg.ts, src/baks/typer.ts
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?onShow=mycards&card=Tea-11399
eosAnnenForelderUtsendtArbeidstaker brukes for å velge delmal
=> Legger til utsendt arbeidstaker slik at vi kan bruke det for å bestemme oss for delmal i sanity

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .github/workflows/build_pr.yaml, Dockerfile
Oppgraderer til node 18 som er nyeste LTS.
Skal ikke være noen breaking changes som treffer oss: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md
Har gjort tilsvarende endring for `familie-ef-sak-frontend` og `familie-klage-frontend` uten problemer.
Har også testet i dev og ting fungerer fint ✅
=> Skal bruke node 18

src/baks/formateringer.ts, src/baks/formateringsvalg.ts, src/baks/typer.ts
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/077068028bffba85055cca2d?card=NAV-12475
Det er ønsket at vi legger til et nytt valgfelt i sanity - deg/dere eller seg.
=> Legger til deg/dere/eller seg valg

src/server/hentAvansertDokumentNavn.ts
For å støtte https://github.com/navikt/familie-sanity-brev/pull/404
=> Skal ta med felt frittstaendeBrev ved henting av brevmaler fra sanity

package.json, src/server/components/serializers/DelmalSerializer.tsx
Se https://github.com/navikt/familie-ba-sak/pull/3795 for mer info
=> Støtt flettefelt som blokk i delmal

src/server/hentAvansertDokumentNavn.ts
Ønsker å hente nytt felt prioriteringsnummer i spørringer, slik at dette kan brukes til å sortere brev.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15425
Sanity-brev: https://github.com/navikt/familie-sanity-brev/pull/449
=> Hente nytt felt prioriteringsnummer i groq spørringer

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
Allerede gjort i ba-sak:
https://github.com/navikt/familie-ba-sak-frontend/pull/2890
=> Bruk GAR for dockercontainere

package.json, yarn.lock
=> bumper date-fns til ny major

.github/dependabot.yml
Det blir sjekket for oppdateringer en gang i uken - på søndager. Det passer bra med vedlikehold på mandager.
=> Ønsker å samle oppdatering fra dependabot. 

src/server/utils/css.ts
Manglet spesifisering av font-familiy for page-elementet i css.ts
=> Fikser problem med PDF-2a compliance etter konvertering fra html i familie-dokument

src/server/blankett/components/InnvilgetBarnetilsyn.tsx, src/server/utils/css.ts, src/server/utils/soknad-css.ts, src/server/utils/util.ts, yarn.lock
Skal gjøre det enklere å se hva saksbehandler har svart, eller det som automatisk kommer fra ks.
Har også tatt med flere av spørsmålene som saksbehandler svarer på.
Slik ser det ut før endringer: 
Etter endringer:
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20231)
=> Strukturert kontantstøtte og tilleggsstønad i blankett

src/server/environment.ts, src/server/sanity/sanityClient.ts
Favrkort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21473
Vi ønsker å bruke nytt og identisk dataset ba-v2 i preprod, den skal senere overta ba-brev.
=> Legg til ba-v2 og bruk det i dev

src/server/blankett/components/KlageBehandling.tsx, src/typer/klageDokumentApi.ts
Legger til hjemler for tilleggsstønader siden de har fått sin klageløsning opp og gå. De bruker familie-brev for å lage blankett. Tillatter meg samtidig å legge inn hjemlene til BA også - de skulle nok ha blitt lagt inn for halvannet år siden :)
=> Hjemler for tilleggsstønader

.build/nais-dev.yaml, .build/nais-prod.yaml, Dockerfile, src/server/environment.ts
Vi setter miljø basert på nais fil istedenfor å ha hardkodet til prod i dockerfil
=> Miljø angitt fra nais fil

Dockerfile
=> Revert dockerfile endringer

src/server/environment.ts
=> Bruk ks-v2 dataset i prod

src/baks/queries.ts, src/server/environment.ts, src/server/sanity/sanityClient.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21842
=> Gå bort i fra ks-v2

src/server/environment.ts, src/server/sanity/sanityClient.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22733
=> Fjerner ba-v2

src/baks/queries.ts, src/server/sanity/sanityClient.ts
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22762
=> Fjern ba test og ks test

.build/nais-dev.yaml, .build/nais-prod.yaml
Skrur på auto-instrumentation som vil sette opp tracing til våre systemer.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21656
=> Legg til auto-instrumentation

src/server/blankett/components/InnvilgetBarnetilsyn.tsx, src/typer/dokumentApiBlankett.ts
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22026)
Legge til den nye beskrivelsen lagt til i kontantstøtte
=> Lagt til kontantsstøttebeskrivelse i blankett

.build/nais-dev.yaml, .build/nais-prod.yaml
Vil slette tilleggsstonader-klage fra inbound - ikke lenger i bruk.
=> Vil slette tilleggsstonader-klage - ikke lenger i bruk.

src/server/blankett/components/KlageBehandling.tsx, src/typer/klageDokumentApi.ts
Legger til nye felter for BA og KS i IVurdering i generering av blankett
Se endringer i [familie-klage](https://github.com/navikt/familie-klage/pull/624)
=> Legg til felter i Vurdering for BA og KS i blankett

.github/dependabot.yml, .github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .github/workflows/build_pr.yaml, .github/workflows/codeql-analysis.yml
💰 Hva forsøker du å løse i denne PR'en
Ta i bruk ratchet og dependabot for github actions. Som vil gi oss up-to-date versjoner av workflows vi bruker. Vi lærte i tech-prat at å lene seg på versjonnummer alene utgir en sikkerhetsrisiko.
=> Pin actions med ratchet
