navikt/familie-brev

- src/server/utils/css.ts
Fant en finere fix. Skjønner ikke helt hvorfor det feiler i utgangspunktet. Det er ingen grunn til at ordet skal brytes 🤷‍♂️
> Finere fix

- src/server/hentAvansertDokumentFelter.ts
Henter alle valgfelter riktig sortert innen for sin delmal. Løses ved at alle valgfelt hentes direkte fra sin omsluttende delmal, istedenfor å gjøre subquery.
> Sorterer valgfelt

- .build/nais-dev.yaml
- .build/nais-prod.yaml
Ref https://nav-it.slack.com/archives/CJN0STWB0/p1622719034046900 så tenker jeg det er bedre å være på den sikre siden. 1MB bør være ganske nøyaktig 1000000 tegn, men jeg vet ikke hvor store de avanserte dokumentene til EF kan bli 🤷‍♂️
> Gjør maks kall-størrelse til 25MB

- src/server/hentAvansertDokumentNavn.ts
- src/server/routes.ts
Brukes i `familie-ef-sak-frontend` for å kunne velge hvilken brevmal man vil bruke. Relevant [Favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5737).
> Legg til endepunkt for å hente navn på avanserte dokumenter

- src/server/hentAvansertDokumentHtml.tsx
Denne PRen fikser delvis feilen der datoen i vedtaksbrev settes til datoen for "send til beslutter" og ikke  "beslutte vedtak".
Datoen settes nå direkte i `familie-brev` istedenfor å ta det inn som et flettefelt. Det betyr at datoen i brevet blir datoen beslutter sist åpner brevfanen. Datoen kan fortsatt bli hvis beslutter åpner brevfanen en på en gitt dato, men først trykker "godkjenn vedtak" ved en senere anledning (uten å ha vært inne på brevfanen den dagen).
> Brevdato i header skal settes til dagens dato direkte i familie-brev

- .husky/pre-commit
- package.json
- yarn.lock
Fjerner ubrukte Npm-pakker.
Oppdaterer npmpakkene.
Flytter husky-kommando ut i `.husky/pre-commit ` siden det er sånn det gjøres i nyere versjoner.
> Oppdater gamler npm-pakker

- src/ba-sak/formateringer.ts
- src/ba-sak/formateringsvalg.ts
- src/ba-sak/typer.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-8367
Endre logikken for valgfeltet "du får/du har rett til" til å ta basere seg på om søker har utbetaling og/eller rett i perioden eller ikke.
- Søker får utbetalt utvidet? Du får
- Søker får ikke utbetalt utvidet, men har rett (dvs. utvidet overstyrt til 0kr)? Du har rett
Spørsmål: 
- Hvordan kan vi sikre at valgfeltet ikke brukes i en begrunnelse som ikke angår utvidet?
Her er eksempel:
- Periode 1: Ikke rett på utvidet, ikke mulig å velge begrunnelser som skal inneholde dette valgfeltet (og hvis det skulle dukke opp på en begrunnelse de klarer å velge så får de en feil)
- Periode 2: Utvidet er overstyrt til 0kr -> du har rett til
- Periode 3: Barn overstyrt til 0kr, men utvidet blir …
> Endre logikk til å se på om søker har utbetaling i perioden eller ikke

- package.json
- src/ba-sak/begrunnelseSerializer.ts
- src/ba-sak/formateringer.ts
- src/server/components/AvansertDokument.tsx
- src/server/components/Dokument.tsx
- src/server/components/serializers/AvansertDelmalSerialaizer.tsx
- src/server/components/serializers/BlockSerializer.tsx
- src/server/components/serializers/DelmalSerializer.tsx
- src/server/components/serializers/FlettefeltSerializer.tsx
- src/server/components/serializers/HtmlfeltSerializer.tsx
- src/server/components/serializers/ListItemSerializer.tsx
- src/server/components/serializers/PeriodeSerializer.tsx
- src/server/components/serializers/ValgfeltSerializer.tsx
- yarn.lock
Migrerer fra `@sanity/block-content-to-react` til `@portabletext/react` etter guide her: https://github.com/portabletext/react-portabletext/blob/main/MIGRATING.md
Prøvde å lage noen tester som bekrefter at HTMLen som genereres er lik, men det ser ut som den nye versjonen wrapper komponentene i færre `div`er uten at det utgjør noen forskjell for hvordan det blir visuelt. Dette gjør det vanskelig å teste på noen annen måte enn med øyenene. 
**Før**
**Nå**
**Før**
**Nå**
**Før**
**Nå**
> Oppdaterer block-content-to-react som er deprecated til PortableText

- src/ba-sak/formateringer.ts
- src/ba-sak/formateringsvalg.ts
- src/ba-sak/typer.ts
Favro: [Tea-9251](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9251)
Begrunnelse for eøs opphør [5. Separasjonsavtalen gjelder ikke](https://familie-brev.sanity.studio/ba-brev/desk/begrunnelse;eos;opphor;1b29f277-28f9-40cd-804a-9f745ff8fab8) krever støtte for å ha formuleringen "deg og eller barnet/barna". 
Legger til støtte for det
> Legg til støtte for deg og eller barnet barna formulering

- src/server/sanity/sanityClient.ts
Uten disse feiler kall med `Datasettet 'ks-brev' finnes ikke`. (datasettet finnes btw 😛 )
> Lagt til datasettene ks-brev og ks-test i Datasett-enum

- src/server/components/serializers/PeriodeSerializer.tsx
Gjør om listen med begrunnelser fra liste til sett for å fjerne identiske begrunnelser.
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-10271
Denne endringen gjør at identiske begrunnelsen i en periode fjernes når man viser brev (pdf). Det er laget en egen PR for å fjerne duplikater i forhåndsvisningen i familie-ba-sak. Se egen PR (https://github.com/navikt/familie-ba-sak/pull/3103).
| Før | Etter    | 
| :---:   | :---: | 
| <img width="740" alt="image" src="https://user-images.githubusercontent.com/46678893/204304291-f7bc490c-8d5d-4b04-b3b2-a5957635f370.png"> | <img width="408" alt="image" src="https://user-images.githubusercontent.com/46678893/204304387-e8cd853d-a49e-4752-a78c-2422d6059837.png"> |
> Fjerne duplikate begrunnelser

- src/server/sanity/Queries.ts
Pga. ulik plassering av curly brackets ble ikke flettefelter innenfor en delmal håndtert på samme måte som utenfor. Har i tillegg til å rette feilen reformatert koden noe, for enklere sammenligning med håndteringen av flettefeltreferanser ovenfor.
> Fikser en bug i hentDelmalQuery:

- src/server/hentAvansertDokumentFelter.ts
I EF-sak har vi behov for å kunne legge til ekstra beskrivelse av valgfelter og flettefelt for å kunne forklare automatiske verdier og slippe lange titler med informasjon i parantes. 
Beskrivelse vil kun hentes om en verdi er gitt (TLDR ingen påvirkning). 
Henger sammen med PR [364](https://github.com/navikt/familie-sanity-brev/pull/364) i familie-sanity-brev
> Hent beskrivelsen til valgfelt med brevstruktur

- src/server/components/AvansertDokument.tsx
- src/server/components/serializers/FritekstområdeSerializer.tsx
- src/server/hentAvansertDokumentFelter.ts
- src/typer/dokumentApi.ts
[Favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11847)
Vi ønsker å kunne legge til fritekstområder i avansert dokument (våre brevmaler) fordi det gjør det mulig å bruke tabell i fritekstbrev <3
Henter fritekstområder fra sanity slik at de sendes med til ef-sak-frontend når brevmenyen skal bygges. 
Lagt til en serializer for fritekstområder som mapper innholdet inn i pdf på riktig sted. 
- [PR i familie-sanity-brev](https://github.com/navikt/familie-sanity-brev/pull/372)
- [PR i familie-brev](https://github.com/navikt/familie-ef-sak-frontend/pull/2165)
> Fritekstområde sanitybrev

- src/server/lagManueltBrevHtml.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12217
Før:
Etter:
> Mer space mellom tekst og hilsen i manuelt brev

- .build/nais-dev.yaml
- .build/nais-prod.yaml
Fikk SSL feil i preprod ved kall mot Sanity. Ser ut til at vi bruker CDN versjon av SanityClient og derfor også må definere CDN url i `outbound.external`.
> Lagt til CDN url for Sanity i preprod og prod

- .build/nais-dev.yaml
- .build/nais-prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
> Fjerner CPU-limit

- .github/workflows/build_n_deploy_dev.yaml
- .github/workflows/build_n_deploy_prod.yaml
- src/baks/formateringsvalg.ts
- src/baks/typer.ts
Favro: [NAV-15586](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15586)
Har slått sammen enumen for `SøkersAktivitet` og `AnnenForeldersAktivitet` til enumen `Aktivitet` da alle aktiviteter kan forekomme for både søker og annen forelder. Man har fortsatt mulighet til å justere valgfelt mulighetene unikt for annen forelder og søker.
> Legger til manglende aktiviteter for søkers og annen forelders aktivitet (EØS praksisendring)

- src/baks/formateringsvalg.ts
- src/baks/typer.ts
Favro: [NAV-15586](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-15586)
Trenger egne valgfelt-muligheter for annen forelder og søker for aktiviteter de deler, da de brukes på en annen måte i "Selvstendig rett"-begrunnelsene enn i øvrige begrunnelser.
Koden som overskrives er ikke tatt i bruk enda og er relatert til praksisendring EØS.
> Lagt til egne valgfelt-muligheter for annen forelder og søker for aktiviteter de deler

- src/server/blankett/components/TidligereHistorikk.tsx
- src/typer/dokumentApiBlankett.ts
Hvorfor ?
Vi trenger å vise tidligere vedtaksperioder for barnetilsyn også i blankett, siden dette også vises i frontend, ref: https://github.com/navikt/familie-ef-sak-frontend/pull/2642
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15808
> Visning av tidligere vedtaksperioder for barnetilsyn

- Dockerfile
I [navikt/baseimages](https://github.com/navikt/baseimages) står det
> NAIS baseimages are not actively maintained and should be considered deprecated.
Consider using official images or preferably distroless alternatives.
Endrer derfor dockerimage til distroless
Testet ok i [preprod](https://github.com/navikt/familie-brev/actions/runs/7845341122/job/21409540461)
> Bruk distroless docker image

- src/server/blankett/components/Header.tsx
- src/server/components/Brevhode.tsx
- src/server/components/Header.tsx
- src/server/søknadgenerator.tsx
- src/server/utils/css.ts
Favro: [NAV-19966](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-19966)
Brevdato ble lest opp til slutt på første side med skjermleser. Vi ønsker at den skal leses opp først. Den kommer først i HTML dokumentet, men etter konvertering til PDF blir den lest opp til slutt. Det er også ønsket at brevdato skal prefixes med `Dato: `. Dette påvirker også brevene til EF.
* Har skrevet om CSS'en til klassene `ikon-og-dato` og `nav-ikon` til å ikke lenger bruke `position: relative` og `position: absolute` og `top: 0`, `right: 0`, og nå blir dato lest opp først på siden. Testet at logo og brevdato fortsatt ser riktig ut. Se skjermbilder under.
* Lagt til `Dato: `-prefix
Til info så ville `float: right` gitt rett leserekkefølge, men det er egentlig bare …
> `Dato: `-prefix for brevdato og oppdatert CSS for ikon og dato i `<Header />`

- src/server/components/Dokument.tsx
- src/server/components/serializers/PeriodeSerializer.tsx
- src/server/components/serializers/SammensattKontrollsakSerializer.tsx
- src/typer/dokumentApiBrev.ts
* Lagt til `SammensattKontrollsakSerializer` og tatt den i bruk i `Dokument`. Dersom `dokumentData` som sendes fra backend inneholder feltet `sammensattKontrollsakFritekst` rendrer vi friteksten.
* Justert `PeriodeSerializer` til å sjekke hvorvidt `dokumentData` inneholder feltet `perioder`. Dersom feltet ikke finnes rendres ingenting.
Bruker altså samme fremgangsmåte i `SammensattKontrollsakSerializer` og `PeriodeSerializer` for å bestemme om vi skal rendre noe eller ikke.
Har en avhengighet til PR i `familie-sanity-brev`: https://github.com/navikt/familie-sanity-brev/pull/609
> Sammensatt kontrollsak: SammensattKontrollsakSerializer for rendring av fritekst i sammensatte kontrollsaker

- src/server/blankett/components/Dokument.tsx
- src/server/blankett/components/InntektGrunnlag.tsx
- src/server/blankett/components/RegistergrunnlagForVilkår.tsx
- src/typer/dokumentApiBlankett.ts
- Refaktorert kode i Dokument - funksjonen registergrunnlagForVilkår er tatt ut i egen fil og laget det som en komponent for å gjøre det mer lesbart. Lagt til nye komponenter/caser. 
- Laget komponenten InntektGrunnlag som viser det samme som blir vist i EF-sak under BT 'Siste periode med overgangsstønad'.
Bildet viser blanketten: 
Bildet viser det som Inntekt under aktivitet i OS:
> Ta med 'Siste periode med overgangsstønad' i blankett

- src/server/blankett/components/AleneomsorgGrunnlag.tsx
- src/server/blankett/components/RegistergrunnlagForVilkår.tsx
- src/typer/dokumentApiBlankett.ts
Ønsker å vise tabell med søker og gjeldene barn sin adresse hvis de ikke bor på samme adresse. Dette er fordi vi viser dette i ef-sak.
Bildet viser hvordan det ser ut i ef-sak. Det ene barnet har samme adresse, mens det andre ikke har det.
Blankett barnet som ikke er registrert på samme adresse:
Registrert på samme adresse:
> Adressevisning hvis ikke samme adresse

- src/typer/dokumentApiBlankett.ts
Fjerner delen av teksten som nevner beløpet - da dette var utdatert og det blir mindre vedlikehold fremover.
> Fjerne beløp fra delvurdering 'inntekt under 6 ganger grunnbeløpet'

- src/server/hentAvansertDokumentFelter.ts
- src/server/routes.ts
- src/server/sanity/sanityClient.ts
Vil legge til nytt endepunkt som bruker nyere versjon av sanity api. Nå bruker vi versjon 1. Legger derfor til ny klient med støtte for å angi versjon (default er v1).
Bytter i første omgang bare ett endepunk brukt av EF (hentAvansertDokumentFelter). 
Må oppdatere groq query. 
(vil legge til toggle for bruk av nytt endepunkt i ef-sak-frontend) 
Testet lokalt. Ser greit ut, men vil gjerne teste dette grundig - vanskelig å være sikker på at alt er som før her. 
Groq queries i sanity studio (vision) ser ut til å returnere samme json.
> Nyere versjon av endepunkt + nyere versjon sanity api

- src/server/hentAvansertDokumentFelter.ts
- src/server/routes.ts
Poc - forenkling og typing. Fortsette, eller tenke annerledes? 
relatert til poc ef-sak-frontend
https://github.com/navikt/familie-ef-sak-frontend/pull/2937
som da gjør at vi kan droppe hele denne delen av groq: 
(router)
const delmaler: Delmaler = await hentDelmaler(datasett, maalform, avansertDokumentNavn, res);
> Forenkling groq

- src/server/components/serializers/FlettefeltSerializer.tsx
Dersom "Er fritekstfelt" er huket av for et flettefelt i Sanity, splittes teksten på `\n\n` og puttes i egne paragraph tags, slik at de kommer på ny linje i PDF'en
> Splitt fritekst på linjeskift

- src/server/index.ts
- src/server/mock/dummyDataNæringsinntekt.json
- src/server/næringsinntekt/components/Header.tsx
- src/server/næringsinntekt/components/Inntekt.tsx
- src/server/næringsinntekt/hentDokumentHtmlNæringsinntekt.tsx
- src/server/næringsinntekt/næringsinntektRoutes.ts
- src/typer/dokumentApiNæringsinntekt.ts
Nytt endepunkt for å lage et notat for ingen endring i inntekt. Dette endepunktet skal tas i bruk i ef-sak hvor inntekten til selvstendig næringsdrivende sjekkes. Testet lokalt.
PR hvor ef-sak kaller dette endepunktet: https://github.com/navikt/familie-ef-sak/pull/2763
> Lag næringsinntekt notat

- src/server/blankett/components/Dokument.tsx
- src/server/blankett/components/InnvilgetBarnetilsyn.tsx
- src/server/blankett/components/Vedtak.tsx
- src/typer/dokumentApiBlankett.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23283
Hvorfor ? 
Trenger å vise kontantstøtteperioder fra KS i blankett. Trenger også en referansedato (ref "hentet" i screenshot). 
ef-sak: https://github.com/navikt/familie-ef-sak/pull/2756
ef-sak-frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/2988
Når kontantstøtteperioder ikke finnes:
> Kontantstøtteperioder

- src/server/blankett/components/KlageBehandling.tsx
- src/server/blankett/genererKlageDokumentHtml.tsx
Sørger for at brevtekst vises på rett sted i blankett avhengig av om den representerer en begrunnelse for ikke-oppfylte vilkår eller for oppfylt klagefrist-unntak.
Screenshots:
Når alle formal-vilkår er oppfylt unntatt klagefrist og klager oppfyller et av unntakene til klagefrist vises fritekst først under "Instillinger til Nav Klageinstans"
Dersom et av de andre formal-vilkårene ikke er oppfylt vises fritekst under "Fritekst til brev" i "Formkrav":
> NAV-24774: Legger til begrunnelse for oppfylt klagefrist-unntak i blankett

- src/server/blankett/components/Dokument.tsx
- src/server/blankett/components/Samværsavtale.tsx
- src/server/blankett/components/Vilkårsvurdering.tsx
- src/server/lagManueltBrevHtml.tsx
- src/server/utils/css.ts
- src/typer/dokumentApiBlankett.ts
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24882)
Skal vise et fullstendig bilde av valgene som ble gjort i samværskalkulatoren i vilkårsfanen. Eksempel:
> Dokumentere samværsberegning

- src/baks/formateringsvalg.ts
Favro: [NAV-25543](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25543)
Det viser seg at vi fortsatt ønsker at annen forelders aktivitet mappes til sanity tekster slik vi alltid har gjort, og at det kun er søkers aktivitet vi ønsker å mappe annerledes ved selvstendig rett.
Korrigerer kode lagt inn i denne PR'en: https://github.com/navikt/familie-brev/pull/795
> Fix: Fjerne selvstendig rett logikk for annen forelders aktivitet

- src/server/components/Header.tsx
- src/server/components/HeaderDeprecated.tsx
- src/server/hentAvansertDokumentHtml.tsx
- src/server/hentDokumentHtml.tsx
- src/typer/dokumentApiBrev.ts
Vi ønsker å vise alle brevmottakere øverst i brevene vi sender slik at de følger Nav sin brevstandard. Den kan man lese mer om her: https://aksel.nav.no/god-praksis/artikler/visuelle-retningslinjer-for-brev
Denne PRen henger sammen med en endring i ef-sak frontend: https://github.com/navikt/familie-ef-sak-frontend/pull/3162
> skal vise alle mottakere av brev øverst i brevet
